"""Naz Lab Phase 1 Text Workstation.

A lightweight Streamlit workstation for general chat and text-generation modes.
It uses Ollama as the local LLM backend and writes outputs, logs, status, and
image job queue items to Google Drive via the Phase 0 shared utilities.
"""

from __future__ import annotations

import json
import sys
import uuid
from datetime import datetime
from pathlib import Path
from typing import Iterable

import requests
import streamlit as st

# Allow running from /content/naz-lab/text_workstation/app.py in Colab.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from shared.drive_paths import (  # noqa: E402
    BASE_PATH,
    CHAT_OUTPUTS,
    IMAGE_JOBS,
    IMAGE_PROMPTS,
    OUTPUT_LOG_JSON,
    SCRIPT_OUTPUTS,
    TEXT_OUTPUTS,
    WORKSTATION_LINKS_JSON,
)
from shared.json_utils import (  # noqa: E402
    append_output_log,
    safe_write_json,
    update_workstation_status,
)

OLLAMA_GENERATE_ENDPOINT = "http://localhost:11434/api/generate"
OLLAMA_HEALTH_ENDPOINT = "http://localhost:11434/api/tags"
DEFAULT_MODEL = "gemma2:2b"
OPTIONAL_MODEL = "mistral"

PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"

MODE_CONFIG = {
    "Story Writer": {
        "prompt_file": "story_writer.md",
        "output_dir": TEXT_OUTPUTS,
        "prefix": "story_writer",
    },
    "Viral Script Writer": {
        "prompt_file": "viral_script_writer.md",
        "output_dir": SCRIPT_OUTPUTS,
        "prefix": "viral_script_writer",
    },
    "Caption Writer": {
        "prompt_file": "caption_writer.md",
        "output_dir": TEXT_OUTPUTS,
        "prefix": "caption_writer",
    },
    "Prompt Improver": {
        "prompt_file": "prompt_improver.md",
        "output_dir": IMAGE_PROMPTS,
        "prefix": "prompt_improver",
    },
}


def now_stamp() -> str:
    return datetime.now().strftime("%Y-%m-%d_%H-%M-%S")


def ensure_phase_0_ready() -> list[str]:
    required = [
        BASE_PATH,
        CHAT_OUTPUTS,
        TEXT_OUTPUTS,
        SCRIPT_OUTPUTS,
        IMAGE_PROMPTS,
        IMAGE_JOBS,
        WORKSTATION_LINKS_JSON,
        OUTPUT_LOG_JSON,
    ]
    missing = [str(path) for path in required if not path.exists()]
    return missing


def read_prompt(prompt_file: str) -> str:
    path = PROMPTS_DIR / prompt_file
    if not path.exists():
        return "You are a helpful Naz Lab assistant."
    return path.read_text(encoding="utf-8").strip()


def call_ollama(prompt: str, model: str, system_prompt: str | None = None) -> str:
    final_prompt = prompt if not system_prompt else f"{system_prompt}\n\nUser:\n{prompt}"
    payload = {
        "model": model,
        "prompt": final_prompt,
        "stream": False,
    }
    response = requests.post(OLLAMA_GENERATE_ENDPOINT, json=payload, timeout=180)
    response.raise_for_status()
    data = response.json()
    return data.get("response", "").strip()


def save_text_output(output_dir: Path, prefix: str, content: str) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{prefix}_{now_stamp()}.txt"
    path.write_text(content, encoding="utf-8")
    append_output_log(
        OUTPUT_LOG_JSON,
        workstation="text_workstation",
        event="output_saved",
        details={"path": str(path), "prefix": prefix},
    )
    update_workstation_status(
        WORKSTATION_LINKS_JSON,
        "text_workstation",
        {"status": "running", "last_output_path": str(path)},
    )
    return path


def create_image_job(prompt_text: str) -> Path:
    IMAGE_JOBS.mkdir(parents=True, exist_ok=True)
    job_id = str(uuid.uuid4())
    job_path = IMAGE_JOBS / f"image_job_{now_stamp()}_{job_id[:8]}.json"
    job_data = {
        "job_id": job_id,
        "source_workstation": "text_workstation",
        "source_mode": "Prompt Improver",
        "status": "pending",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "prompt": prompt_text,
        "notes": "Generated by Text Workstation Prompt Improver",
    }
    safe_write_json(job_path, job_data)
    append_output_log(
        OUTPUT_LOG_JSON,
        workstation="text_workstation",
        event="image_job_created",
        details={"job_path": str(job_path), "job_id": job_id},
    )
    return job_path


def list_text_files(directories: Iterable[Path]) -> list[Path]:
    files: list[Path] = []
    for directory in directories:
        if directory.exists():
            files.extend(directory.glob("*.txt"))
    return sorted(files, key=lambda p: p.stat().st_mtime, reverse=True)


def save_chat_transcript(messages: list[dict[str, str]]) -> Path:
    lines = []
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        lines.append(f"[{role}]\n{content}\n")
    return save_text_output(CHAT_OUTPUTS, "chat", "\n".join(lines))


def render_general_chat(model: str) -> None:
    st.subheader("General Chat")
    st.caption("Normal assistant mode. Ask about anything: content, Colab, coding, business, prompts, planning, and general knowledge.")

    system_prompt = read_prompt("general_chat.md")

    if "chat_messages" not in st.session_state:
        st.session_state.chat_messages = []

    col_a, col_b = st.columns(2)
    with col_a:
        if st.button("Clear Chat"):
            st.session_state.chat_messages = []
            st.rerun()
    with col_b:
        if st.button("Save Chat"):
            if st.session_state.chat_messages:
                path = save_chat_transcript(st.session_state.chat_messages)
                st.success(f"Chat saved: {path}")
            else:
                st.info("No chat messages to save yet.")

    for message in st.session_state.chat_messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    user_prompt = st.chat_input("Message Naz Lab General Assistant...")
    if user_prompt:
        st.session_state.chat_messages.append({"role": "user", "content": user_prompt})
        with st.chat_message("user"):
            st.markdown(user_prompt)

        conversation = "\n".join(
            f"{m['role'].upper()}: {m['content']}" for m in st.session_state.chat_messages[-10:]
        )
        try:
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    answer = call_ollama(conversation, model=model, system_prompt=system_prompt)
                    st.markdown(answer)
            st.session_state.chat_messages.append({"role": "assistant", "content": answer})
        except Exception as exc:
            st.error(f"Ollama connection error: {exc}")


def render_writer_mode(mode: str, model: str) -> None:
    config = MODE_CONFIG[mode]
    st.subheader(mode)
    system_prompt = read_prompt(config["prompt_file"])
    user_input = st.text_area("Input context or topic", height=180, key=f"input_{mode}")

    if st.button(f"Generate {mode}", key=f"generate_{mode}"):
        if not user_input.strip():
            st.warning("Please provide input first.")
            return
        try:
            with st.spinner("Generating..."):
                result = call_ollama(user_input, model=model, system_prompt=system_prompt)
            st.markdown("### Output")
            st.write(result)
            path = save_text_output(config["output_dir"], config["prefix"], result)
            st.success(f"Saved: {path}")

            if mode == "Prompt Improver":
                job_path = create_image_job(result)
                st.success(f"Image job created: {job_path}")
        except Exception as exc:
            st.error(f"Ollama connection error: {exc}")


def render_output_library() -> None:
    st.subheader("Output Library")
    files = list_text_files([CHAT_OUTPUTS, TEXT_OUTPUTS, SCRIPT_OUTPUTS, IMAGE_PROMPTS])
    if not files:
        st.info("No saved outputs yet.")
        return

    display = [str(path) for path in files[:50]]
    selected = st.selectbox("Select output file", display)
    if selected:
        path = Path(selected)
        st.caption(str(path))
        st.text_area("Preview", path.read_text(encoding="utf-8"), height=300)


def render_settings(model: str) -> None:
    st.subheader("Settings")
    public_url = st.text_input("Public Cloudflare URL", value="")
    if st.button("Save Public URL"):
        update_workstation_status(
            WORKSTATION_LINKS_JSON,
            "text_workstation",
            {"public_url": public_url, "last_url_updated": datetime.now().isoformat(timespec="seconds")},
        )
        st.success("Public URL saved to workstation_links.json")

    if st.button("Check Ollama Health"):
        try:
            response = requests.get(OLLAMA_HEALTH_ENDPOINT, timeout=15)
            response.raise_for_status()
            st.json(response.json())
        except Exception as exc:
            st.error(f"Ollama health check failed: {exc}")

    st.markdown("### Paths")
    st.write({
        "model": model,
        "generate_endpoint": OLLAMA_GENERATE_ENDPOINT,
        "health_endpoint": OLLAMA_HEALTH_ENDPOINT,
        "base_path": str(BASE_PATH),
        "chat_outputs": str(CHAT_OUTPUTS),
        "text_outputs": str(TEXT_OUTPUTS),
        "script_outputs": str(SCRIPT_OUTPUTS),
        "image_prompts": str(IMAGE_PROMPTS),
        "image_jobs": str(IMAGE_JOBS),
        "workstation_links_json": str(WORKSTATION_LINKS_JSON),
        "output_log_json": str(OUTPUT_LOG_JSON),
    })


def main() -> None:
    st.set_page_config(page_title="Naz Lab Text Workstation", page_icon="✍️", layout="wide")
    st.title("✍️ Naz Lab Text Workstation")
    st.caption("Phase 1: General Chat, Story, Viral Script, Caption, Prompt Improver")

    missing = ensure_phase_0_ready()
    if missing:
        st.error("Phase 0 foundation appears incomplete. Run master_setup/init_drive_structure.py first.")
        st.code("\n".join(missing))
        return

    update_workstation_status(WORKSTATION_LINKS_JSON, "text_workstation", {"status": "running"})

    with st.sidebar:
        st.header("Naz Lab Core")
        model = st.selectbox("Model", [DEFAULT_MODEL, OPTIONAL_MODEL], index=0)
        page = st.radio(
            "Mode",
            [
                "General Chat",
                "Story Writer",
                "Viral Script Writer",
                "Caption Writer",
                "Prompt Improver",
                "Output Library",
                "Settings",
            ],
        )
        st.caption("Cloudflare Tunnel is primary. Localtunnel is fallback only.")

    if page == "General Chat":
        render_general_chat(model)
    elif page in MODE_CONFIG:
        render_writer_mode(page, model)
    elif page == "Output Library":
        render_output_library()
    elif page == "Settings":
        render_settings(model)


if __name__ == "__main__":
    main()
